baseurl: "https://www.elm-conf.us/"
languageCode: "en-us"
title: "elm-conf 2016"
theme: "elm-conf"
params:
  date: September 15, 2016
  location: St. Louis, Missouri

  # CFP info
  cfp_start: 'June 1, 2016'
  cfp_end: 'June 31, 2016'
  cfp_notify: 'July 8, 2016'

  # Contact
  email: elm-conf@thestrangeloop.com
  twitter: ElmConf
  twitter_hashtag: "#ElmConf"
