baseurl: "https://www.elm-conf.us/"
languageCode: "en-us"
title: "elm-conf 2016"
theme: "elm-conf"
params:
  date: September 15, 2016
  location: St. Louis, Missouri

  # CFP info
  cfp_start: '{cfp start}'
  cfp_end: '{cfp end}'
  cfp_notify: '{cfp result notification date}'
